# Generated by Django 4.2.5 on 2023-09-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('birth_date', models.DateField()),
                ('image', models.ImageField(upload_to='prof_pc/')),
                ('blood', models.CharField(choices=[('B+', 'B+'), ('B-', 'B-'), ('A+', 'A+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O-', 'O-'), ('O+', 'O+')], max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=50)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Buddha', 'Buddha'), ('Others', 'Others')], max_length=50)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
